
export { default as MShape } from './shape'
export * from './interface'

export const MDUI_SHAPES = [
  "circle",
  "rectangle",
  "slanted",
  "arch",
  "semicircle",
  "oval",
  "pill",
  "triangle",
  "arrow",
  "fan",
  "diamond",
  "clamshell",
  "pentagon",
  "gem",
  "verSunny",
  "sunny",
  "fourSidedCookie",
  "sixSidedCookie",
  "sevenSidedCookie",
  "nineSidedCookie",
  "12SidedCookie",
  "4LeafClover",
  "8LeafClover",
  "burst",
  "softBurst",
  "boom",
  "softBoom",
  "flower",
  "puffy",
  "puffyDiamond",
  "ghostIsh",
  "pixelCircle",
  "pixelTriangle",
  "bun",
  "heart",
];
